### ISSUE TITLE
Write better documentation

### ISSUE THREAD

**Issue by JustJoostNL** [JustJoostNL/F1MV-Lights-Integration#14]

**Comment by LapsTimeOFF** [comment]
I recommend you to create a [VuePress](https://v2.vuepress.vuejs.org/) docs in GitHub pages, it's way more complete than Wiki

**Comment by JustJoostNL** [comment]
Thanks for your recommendation! I am currently building a beautiful VuePress website!

**Comment by JustJoostNL** [comment]
New documentation can be found here: https://lightsintegration.joost.systems
