### ISSUE TITLE
Blinking lights for different flags

### ISSUE THREAD

**Issue by Hurri1Kane** [JustJoostNL/F1MV-Lights-Integration#24]
Hey, I would love to have a blinking light feature for Nanoleaf. It would be perfect for double yellow flag etc.

I'm no coder, so I don't know if this is possible, but it would have been really cool.

**Comment by Hurri1Kane** [comment]
Any news on this feature?

**Comment by JustJoostNL** [comment]
Double yellow flag would be hard. But I am currently working on other effects. Such as blinking on VSC ending.

**Comment by JustJoostNL** [comment]
The first version of this is implemented in V1.1.8. With more effects, and custom effects coming soon! 😄
