### ISSUE TITLE
MacOS ARM 2.2.2 Javascrip error when opening

### ISSUE THREAD

**Issue by krugdm** [JustJoostNL/F1MV-Lights-Integration#41]
MacOS ARM v. 2.2.2, I get a Javascript error immediately when opening, and the app is nonfunctional after closing the error window.

`Uncaught Exception:
Error: Cannot find module 'node-aead-crypto-darwin-arm64'
Require stack:
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/node_modules/node-aead-crypto/lib.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/node_modules/node-aead-crypto/index.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/node_modules/node-dtls-client/build/lib/AEADCrypto.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/node_modules/node-dtls-client/build/TLS/AEADCipher.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/node_modules/node-dtls-client/build/TLS/CipherSuite.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/node_modules/node-dtls-client/build/DTLS/Handshake.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/node_modules/node-dtls-client/build/dtls.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/node_modules/node-coap-client/build/CoapClient.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/node_modules/node-tradfri-client/build/tradfri-client.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/node_modules/node-tradfri-client/build/index.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/dist-electron/main/app/integrations/ikea/discoverIkeaBridge.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/dist-electron/main/app/integrations/ikea/ikeaInit.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/dist-electron/main/config/config.js
- /Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/dist-electron/main/index.js
- 
at Module._resolveFilename (node:internal/modules/cjs/loader:1002:15)
at n._resolveFilename (node:electron/js2c/browser_init:2:109734)
at Module._load (node:internal/modules/cjs/loader:848:27)
at f._load (node:electron/js2c/asar_bundle:2:13330)
at Module.require (node:internal/modules/cjs/loader:1068:19)
at require (node:internal/modules/cjs/helpers:103:18)
at Object.<anonymous> (/Applications/F1MV-Lights-Integration.app/Contents/Resources/app.asar/node_modules/node-aead-crypto/lib.js:135:29)
at Module._compile (node:internal/modules/cjs/loader:1174:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
`

**Comment by JustJoostNL** [comment]
Thanks for the report! I am currently trying to solve this! 😄

**Comment by krugdm** [comment]
I blame the lizards.

**Comment by JustJoostNL** [comment]
Fixed in the latest version.
