### ISSUE TITLE
iFlag Integration 

### ISSUE THREAD

**Issue by AlexWHughes** [JustJoostNL/F1MV-Lights-Integration#42]
I've got two of these devices. I'd be keen to work out if its possible to make it work and replicate similar LED states to the real track side panels. Happy to contribute 

https://www.symprojects.com/iflag-for-iracing

**Comment by JustJoostNL** [comment]
Hey, I think this would fit better in the F1MV Digiflag integration (https://github.com/LapsTimeOFF/DigiFlag_F1MV). They already have support for virtual flag panels, and the Divoom Pixoo 64. Could you open an issue there?
