### ISSUE TITLE
App cannot be minimized

### ISSUE THREAD

**Issue by marnick100** [JustJoostNL/F1MV-Lights-Integration#44]
Hi, i have an issue where the program can't minimize.

**Comment by JustJoostNL** [comment]
Hey @marnick100

Minimizing is disabled because you will get background throttling (so lights will end up switching from color way slower, or in a bad case they don't switch at all).

**Comment by T3CHmaster26** [comment]
> Hey @marnick100
> 
> Minimizing is disabled because you will get background throttling (so lights will end up switching from color way slower, or in a bad case they don't switch at all).

Would it be possible to allow for a smaller on screen footprint instead?

**Comment by JustJoostNL** [comment]
@T3CHmaster26 In the next update minimizing will be enabled.
